// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="real_matmul_real_matmul,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.040000,HLS_SYN_LAT=90165,HLS_SYN_TPT=none,HLS_SYN_MEM=146,HLS_SYN_DSP=0,HLS_SYN_FF=9234,HLS_SYN_LUT=21175,HLS_VERSION=2024_1}" *)

module real_matmul (
        ap_clk,
        ap_rst_n,
        m_axi_mem_AWVALID,
        m_axi_mem_AWREADY,
        m_axi_mem_AWADDR,
        m_axi_mem_AWID,
        m_axi_mem_AWLEN,
        m_axi_mem_AWSIZE,
        m_axi_mem_AWBURST,
        m_axi_mem_AWLOCK,
        m_axi_mem_AWCACHE,
        m_axi_mem_AWPROT,
        m_axi_mem_AWQOS,
        m_axi_mem_AWREGION,
        m_axi_mem_AWUSER,
        m_axi_mem_WVALID,
        m_axi_mem_WREADY,
        m_axi_mem_WDATA,
        m_axi_mem_WSTRB,
        m_axi_mem_WLAST,
        m_axi_mem_WID,
        m_axi_mem_WUSER,
        m_axi_mem_ARVALID,
        m_axi_mem_ARREADY,
        m_axi_mem_ARADDR,
        m_axi_mem_ARID,
        m_axi_mem_ARLEN,
        m_axi_mem_ARSIZE,
        m_axi_mem_ARBURST,
        m_axi_mem_ARLOCK,
        m_axi_mem_ARCACHE,
        m_axi_mem_ARPROT,
        m_axi_mem_ARQOS,
        m_axi_mem_ARREGION,
        m_axi_mem_ARUSER,
        m_axi_mem_RVALID,
        m_axi_mem_RREADY,
        m_axi_mem_RDATA,
        m_axi_mem_RLAST,
        m_axi_mem_RID,
        m_axi_mem_RUSER,
        m_axi_mem_RRESP,
        m_axi_mem_BVALID,
        m_axi_mem_BREADY,
        m_axi_mem_BRESP,
        m_axi_mem_BID,
        m_axi_mem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 147'd1;
parameter    ap_ST_fsm_state2 = 147'd2;
parameter    ap_ST_fsm_state3 = 147'd4;
parameter    ap_ST_fsm_state4 = 147'd8;
parameter    ap_ST_fsm_state5 = 147'd16;
parameter    ap_ST_fsm_state6 = 147'd32;
parameter    ap_ST_fsm_state7 = 147'd64;
parameter    ap_ST_fsm_state8 = 147'd128;
parameter    ap_ST_fsm_state9 = 147'd256;
parameter    ap_ST_fsm_state10 = 147'd512;
parameter    ap_ST_fsm_state11 = 147'd1024;
parameter    ap_ST_fsm_state12 = 147'd2048;
parameter    ap_ST_fsm_state13 = 147'd4096;
parameter    ap_ST_fsm_state14 = 147'd8192;
parameter    ap_ST_fsm_state15 = 147'd16384;
parameter    ap_ST_fsm_state16 = 147'd32768;
parameter    ap_ST_fsm_state17 = 147'd65536;
parameter    ap_ST_fsm_state18 = 147'd131072;
parameter    ap_ST_fsm_state19 = 147'd262144;
parameter    ap_ST_fsm_state20 = 147'd524288;
parameter    ap_ST_fsm_state21 = 147'd1048576;
parameter    ap_ST_fsm_state22 = 147'd2097152;
parameter    ap_ST_fsm_state23 = 147'd4194304;
parameter    ap_ST_fsm_state24 = 147'd8388608;
parameter    ap_ST_fsm_state25 = 147'd16777216;
parameter    ap_ST_fsm_state26 = 147'd33554432;
parameter    ap_ST_fsm_state27 = 147'd67108864;
parameter    ap_ST_fsm_state28 = 147'd134217728;
parameter    ap_ST_fsm_state29 = 147'd268435456;
parameter    ap_ST_fsm_state30 = 147'd536870912;
parameter    ap_ST_fsm_state31 = 147'd1073741824;
parameter    ap_ST_fsm_state32 = 147'd2147483648;
parameter    ap_ST_fsm_state33 = 147'd4294967296;
parameter    ap_ST_fsm_state34 = 147'd8589934592;
parameter    ap_ST_fsm_state35 = 147'd17179869184;
parameter    ap_ST_fsm_state36 = 147'd34359738368;
parameter    ap_ST_fsm_state37 = 147'd68719476736;
parameter    ap_ST_fsm_state38 = 147'd137438953472;
parameter    ap_ST_fsm_state39 = 147'd274877906944;
parameter    ap_ST_fsm_state40 = 147'd549755813888;
parameter    ap_ST_fsm_state41 = 147'd1099511627776;
parameter    ap_ST_fsm_state42 = 147'd2199023255552;
parameter    ap_ST_fsm_state43 = 147'd4398046511104;
parameter    ap_ST_fsm_state44 = 147'd8796093022208;
parameter    ap_ST_fsm_state45 = 147'd17592186044416;
parameter    ap_ST_fsm_state46 = 147'd35184372088832;
parameter    ap_ST_fsm_state47 = 147'd70368744177664;
parameter    ap_ST_fsm_state48 = 147'd140737488355328;
parameter    ap_ST_fsm_state49 = 147'd281474976710656;
parameter    ap_ST_fsm_state50 = 147'd562949953421312;
parameter    ap_ST_fsm_state51 = 147'd1125899906842624;
parameter    ap_ST_fsm_state52 = 147'd2251799813685248;
parameter    ap_ST_fsm_state53 = 147'd4503599627370496;
parameter    ap_ST_fsm_state54 = 147'd9007199254740992;
parameter    ap_ST_fsm_state55 = 147'd18014398509481984;
parameter    ap_ST_fsm_state56 = 147'd36028797018963968;
parameter    ap_ST_fsm_state57 = 147'd72057594037927936;
parameter    ap_ST_fsm_state58 = 147'd144115188075855872;
parameter    ap_ST_fsm_state59 = 147'd288230376151711744;
parameter    ap_ST_fsm_state60 = 147'd576460752303423488;
parameter    ap_ST_fsm_state61 = 147'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 147'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 147'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 147'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 147'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 147'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 147'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 147'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 147'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 147'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 147'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 147'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 147'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 147'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 147'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 147'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 147'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 147'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 147'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 147'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 147'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 147'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 147'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 147'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 147'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 147'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 147'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 147'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 147'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 147'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 147'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 147'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 147'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 147'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 147'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 147'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 147'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 147'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 147'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 147'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 147'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 147'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 147'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 147'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 147'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 147'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 147'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 147'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 147'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 147'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 147'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 147'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 147'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 147'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 147'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 147'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 147'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 147'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 147'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 147'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 147'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 147'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 147'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 147'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 147'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 147'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 147'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 147'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 147'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 147'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 147'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 147'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state133 = 147'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state134 = 147'd10889035741470030830827987437816582766592;
parameter    ap_ST_fsm_state135 = 147'd21778071482940061661655974875633165533184;
parameter    ap_ST_fsm_state136 = 147'd43556142965880123323311949751266331066368;
parameter    ap_ST_fsm_state137 = 147'd87112285931760246646623899502532662132736;
parameter    ap_ST_fsm_state138 = 147'd174224571863520493293247799005065324265472;
parameter    ap_ST_fsm_state139 = 147'd348449143727040986586495598010130648530944;
parameter    ap_ST_fsm_state140 = 147'd696898287454081973172991196020261297061888;
parameter    ap_ST_fsm_state141 = 147'd1393796574908163946345982392040522594123776;
parameter    ap_ST_fsm_state142 = 147'd2787593149816327892691964784081045188247552;
parameter    ap_ST_fsm_state143 = 147'd5575186299632655785383929568162090376495104;
parameter    ap_ST_fsm_state144 = 147'd11150372599265311570767859136324180752990208;
parameter    ap_ST_fsm_state145 = 147'd22300745198530623141535718272648361505980416;
parameter    ap_ST_fsm_state146 = 147'd44601490397061246283071436545296723011960832;
parameter    ap_ST_fsm_state147 = 147'd89202980794122492566142873090593446023921664;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_ID_WIDTH = 1;
parameter    C_M_AXI_MEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_MEM_DATA_WIDTH = 128;
parameter    C_M_AXI_MEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_USER_VALUE = 0;
parameter    C_M_AXI_MEM_PROT_VALUE = 0;
parameter    C_M_AXI_MEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEM_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_mem_AWVALID;
input   m_axi_mem_AWREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_AWADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_AWID;
output  [7:0] m_axi_mem_AWLEN;
output  [2:0] m_axi_mem_AWSIZE;
output  [1:0] m_axi_mem_AWBURST;
output  [1:0] m_axi_mem_AWLOCK;
output  [3:0] m_axi_mem_AWCACHE;
output  [2:0] m_axi_mem_AWPROT;
output  [3:0] m_axi_mem_AWQOS;
output  [3:0] m_axi_mem_AWREGION;
output  [C_M_AXI_MEM_AWUSER_WIDTH - 1:0] m_axi_mem_AWUSER;
output   m_axi_mem_WVALID;
input   m_axi_mem_WREADY;
output  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_WDATA;
output  [C_M_AXI_MEM_WSTRB_WIDTH - 1:0] m_axi_mem_WSTRB;
output   m_axi_mem_WLAST;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_WID;
output  [C_M_AXI_MEM_WUSER_WIDTH - 1:0] m_axi_mem_WUSER;
output   m_axi_mem_ARVALID;
input   m_axi_mem_ARREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_ARADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_ARID;
output  [7:0] m_axi_mem_ARLEN;
output  [2:0] m_axi_mem_ARSIZE;
output  [1:0] m_axi_mem_ARBURST;
output  [1:0] m_axi_mem_ARLOCK;
output  [3:0] m_axi_mem_ARCACHE;
output  [2:0] m_axi_mem_ARPROT;
output  [3:0] m_axi_mem_ARQOS;
output  [3:0] m_axi_mem_ARREGION;
output  [C_M_AXI_MEM_ARUSER_WIDTH - 1:0] m_axi_mem_ARUSER;
input   m_axi_mem_RVALID;
output   m_axi_mem_RREADY;
input  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_RDATA;
input   m_axi_mem_RLAST;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_RID;
input  [C_M_AXI_MEM_RUSER_WIDTH - 1:0] m_axi_mem_RUSER;
input  [1:0] m_axi_mem_RRESP;
input   m_axi_mem_BVALID;
output   m_axi_mem_BREADY;
input  [1:0] m_axi_mem_BRESP;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_BID;
input  [C_M_AXI_MEM_BUSER_WIDTH - 1:0] m_axi_mem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [146:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] MatA_DRAM;
wire   [63:0] MatB_DRAM;
wire   [63:0] MatC_DRAM;
reg    mem_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    mem_blk_n_AW;
wire    ap_CS_fsm_state77;
reg    mem_blk_n_B;
wire    ap_CS_fsm_state147;
reg   [63:0] MatA_DRAM_read_reg_206;
reg    ap_block_state1;
reg   [59:0] trunc_ln_reg_211;
reg   [59:0] trunc_ln3_reg_217;
reg    mem_AWVALID;
wire    mem_AWREADY;
reg   [63:0] mem_AWADDR;
reg   [31:0] mem_AWLEN;
reg    mem_WVALID;
wire    mem_WREADY;
reg    mem_ARVALID;
wire    mem_ARREADY;
reg   [63:0] mem_ARADDR;
reg   [31:0] mem_ARLEN;
wire    mem_RVALID;
reg    mem_RREADY;
wire   [127:0] mem_RDATA;
wire   [8:0] mem_RFIFONUM;
wire    mem_BVALID;
reg    mem_BREADY;
wire    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_done;
reg   [6:0] MatA_address0;
reg    MatA_ce0;
reg    MatA_we0;
wire   [2399:0] MatA_q0;
reg    MatA_ce1;
wire   [2399:0] MatA_q1;
reg   [7:0] MatB_address0;
reg    MatB_ce0;
reg   [299:0] MatB_we0;
wire   [2399:0] MatB_q0;
reg   [14:0] MatC_address0;
reg    MatC_ce0;
reg    MatC_we0;
reg   [15:0] MatC_d0;
wire   [15:0] MatC_q0;
reg    MatC_ce1;
wire   [15:0] MatC_q1;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_start;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_done;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_idle;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_ready;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWVALID;
wire   [63:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWADDR;
wire   [0:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWID;
wire   [31:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWLEN;
wire   [2:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWSIZE;
wire   [1:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWBURST;
wire   [1:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWLOCK;
wire   [3:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWCACHE;
wire   [2:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWPROT;
wire   [3:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWQOS;
wire   [3:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWREGION;
wire   [0:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWUSER;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WVALID;
wire   [127:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WDATA;
wire   [15:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WSTRB;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WLAST;
wire   [0:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WID;
wire   [0:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WUSER;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARVALID;
wire   [63:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARADDR;
wire   [0:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARID;
wire   [31:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARLEN;
wire   [2:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARSIZE;
wire   [1:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARBURST;
wire   [1:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARLOCK;
wire   [3:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARCACHE;
wire   [2:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARPROT;
wire   [3:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARQOS;
wire   [3:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARREGION;
wire   [0:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARUSER;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_RREADY;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_BREADY;
wire   [6:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_address0;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_ce0;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_we0;
wire   [2399:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_d0;
wire   [6:0] grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_address1;
wire    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_ce1;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_start;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_done;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_idle;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_ready;
wire   [14:0] grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_address0;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_ce0;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_we0;
wire   [15:0] grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_d0;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_start;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_done;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_idle;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_ready;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWVALID;
wire   [63:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWADDR;
wire   [0:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWID;
wire   [31:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWLEN;
wire   [2:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWSIZE;
wire   [1:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWBURST;
wire   [1:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWLOCK;
wire   [3:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWCACHE;
wire   [2:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWPROT;
wire   [3:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWQOS;
wire   [3:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWREGION;
wire   [0:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWUSER;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WVALID;
wire   [127:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WDATA;
wire   [15:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WSTRB;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WLAST;
wire   [0:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WID;
wire   [0:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WUSER;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARVALID;
wire   [63:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARADDR;
wire   [0:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARID;
wire   [31:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARLEN;
wire   [2:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARSIZE;
wire   [1:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARBURST;
wire   [1:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARLOCK;
wire   [3:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARCACHE;
wire   [2:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARPROT;
wire   [3:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARQOS;
wire   [3:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARREGION;
wire   [0:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARUSER;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_RREADY;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_BREADY;
wire   [7:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_address0;
wire    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_ce0;
wire   [299:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_we0;
wire   [2399:0] grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_d0;
wire    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_start;
wire    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_idle;
wire    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_ready;
wire   [6:0] grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatA_address0;
wire    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatA_ce0;
wire   [14:0] grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_address0;
wire    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_ce0;
wire    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_we0;
wire   [15:0] grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_d0;
wire   [14:0] grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_address1;
wire    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_ce1;
wire   [7:0] grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatB_address0;
wire    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatB_ce0;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_start;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_done;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_idle;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_ready;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWVALID;
wire   [63:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWADDR;
wire   [0:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWID;
wire   [31:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWLEN;
wire   [2:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWSIZE;
wire   [1:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWBURST;
wire   [1:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWLOCK;
wire   [3:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWCACHE;
wire   [2:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWPROT;
wire   [3:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWQOS;
wire   [3:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWREGION;
wire   [0:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWUSER;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WVALID;
wire   [127:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WDATA;
wire   [15:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WSTRB;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WLAST;
wire   [0:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WID;
wire   [0:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WUSER;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARVALID;
wire   [63:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARADDR;
wire   [0:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARID;
wire   [31:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARLEN;
wire   [2:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARSIZE;
wire   [1:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARBURST;
wire   [1:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARLOCK;
wire   [3:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARCACHE;
wire   [2:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARPROT;
wire   [3:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARQOS;
wire   [3:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARREGION;
wire   [0:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARUSER;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_RREADY;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_BREADY;
wire   [14:0] grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_MatC_address0;
wire    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_MatC_ce0;
reg    grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_start_reg;
reg    ap_block_state1_ignore_call18;
wire    ap_CS_fsm_state2;
reg    grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_start_reg;
reg    ap_block_state1_ignore_call24;
reg    grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_start_reg;
wire    ap_CS_fsm_state74;
wire    ap_CS_fsm_state75;
reg    grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_start_reg;
wire    ap_CS_fsm_state76;
reg    grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_start_reg;
wire    ap_CS_fsm_state78;
wire    ap_CS_fsm_state79;
wire  signed [63:0] sext_ln36_fu_186_p1;
wire  signed [63:0] sext_ln71_fu_196_p1;
reg   [146:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
reg    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
reg    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
reg    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
wire    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
wire    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
wire    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
wire    ap_ST_fsm_state110_blk;
wire    ap_ST_fsm_state111_blk;
wire    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
wire    ap_ST_fsm_state114_blk;
wire    ap_ST_fsm_state115_blk;
wire    ap_ST_fsm_state116_blk;
wire    ap_ST_fsm_state117_blk;
wire    ap_ST_fsm_state118_blk;
wire    ap_ST_fsm_state119_blk;
wire    ap_ST_fsm_state120_blk;
wire    ap_ST_fsm_state121_blk;
wire    ap_ST_fsm_state122_blk;
wire    ap_ST_fsm_state123_blk;
wire    ap_ST_fsm_state124_blk;
wire    ap_ST_fsm_state125_blk;
wire    ap_ST_fsm_state126_blk;
wire    ap_ST_fsm_state127_blk;
wire    ap_ST_fsm_state128_blk;
wire    ap_ST_fsm_state129_blk;
wire    ap_ST_fsm_state130_blk;
wire    ap_ST_fsm_state131_blk;
wire    ap_ST_fsm_state132_blk;
wire    ap_ST_fsm_state133_blk;
wire    ap_ST_fsm_state134_blk;
wire    ap_ST_fsm_state135_blk;
wire    ap_ST_fsm_state136_blk;
wire    ap_ST_fsm_state137_blk;
wire    ap_ST_fsm_state138_blk;
wire    ap_ST_fsm_state139_blk;
wire    ap_ST_fsm_state140_blk;
wire    ap_ST_fsm_state141_blk;
wire    ap_ST_fsm_state142_blk;
wire    ap_ST_fsm_state143_blk;
wire    ap_ST_fsm_state144_blk;
wire    ap_ST_fsm_state145_blk;
wire    ap_ST_fsm_state146_blk;
reg    ap_ST_fsm_state147_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 147'd1;
#0 grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_start_reg = 1'b0;
#0 grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_start_reg = 1'b0;
#0 grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_start_reg = 1'b0;
#0 grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_start_reg = 1'b0;
#0 grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_start_reg = 1'b0;
end

real_matmul_MatA_RAM_AUTO_1R1W #(
    .DataWidth( 2400 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
MatA_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatA_address0),
    .ce0(MatA_ce0),
    .we0(MatA_we0),
    .d0(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_d0),
    .q0(MatA_q0),
    .address1(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_address1),
    .ce1(MatA_ce1),
    .q1(MatA_q1)
);

real_matmul_MatB_RAM_AUTO_1R1W #(
    .DataWidth( 2400 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
MatB_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatB_address0),
    .ce0(MatB_ce0),
    .we0(MatB_we0),
    .d0(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_d0),
    .q0(MatB_q0)
);

real_matmul_MatC_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 20000 ),
    .AddressWidth( 15 ))
MatC_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(MatC_address0),
    .ce0(MatC_ce0),
    .we0(MatC_we0),
    .d0(MatC_d0),
    .q0(MatC_q0),
    .address1(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_address1),
    .ce1(MatC_ce1),
    .q1(MatC_q1)
);

real_matmul_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_start),
    .ap_done(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_done),
    .ap_idle(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_idle),
    .ap_ready(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_ready),
    .m_axi_mem_AWVALID(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWVALID),
    .m_axi_mem_AWREADY(1'b0),
    .m_axi_mem_AWADDR(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWADDR),
    .m_axi_mem_AWID(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWID),
    .m_axi_mem_AWLEN(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWLEN),
    .m_axi_mem_AWSIZE(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWSIZE),
    .m_axi_mem_AWBURST(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWBURST),
    .m_axi_mem_AWLOCK(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWLOCK),
    .m_axi_mem_AWCACHE(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWCACHE),
    .m_axi_mem_AWPROT(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWPROT),
    .m_axi_mem_AWQOS(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWQOS),
    .m_axi_mem_AWREGION(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWREGION),
    .m_axi_mem_AWUSER(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_AWUSER),
    .m_axi_mem_WVALID(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WVALID),
    .m_axi_mem_WREADY(1'b0),
    .m_axi_mem_WDATA(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WDATA),
    .m_axi_mem_WSTRB(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WSTRB),
    .m_axi_mem_WLAST(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WLAST),
    .m_axi_mem_WID(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WID),
    .m_axi_mem_WUSER(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_WUSER),
    .m_axi_mem_ARVALID(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARVALID),
    .m_axi_mem_ARREADY(mem_ARREADY),
    .m_axi_mem_ARADDR(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARADDR),
    .m_axi_mem_ARID(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARID),
    .m_axi_mem_ARLEN(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARLEN),
    .m_axi_mem_ARSIZE(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARSIZE),
    .m_axi_mem_ARBURST(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARBURST),
    .m_axi_mem_ARLOCK(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARLOCK),
    .m_axi_mem_ARCACHE(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARCACHE),
    .m_axi_mem_ARPROT(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARPROT),
    .m_axi_mem_ARQOS(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARQOS),
    .m_axi_mem_ARREGION(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARREGION),
    .m_axi_mem_ARUSER(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARUSER),
    .m_axi_mem_RVALID(mem_RVALID),
    .m_axi_mem_RREADY(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_RREADY),
    .m_axi_mem_RDATA(mem_RDATA),
    .m_axi_mem_RLAST(1'b0),
    .m_axi_mem_RID(1'd0),
    .m_axi_mem_RFIFONUM(mem_RFIFONUM),
    .m_axi_mem_RUSER(1'd0),
    .m_axi_mem_RRESP(2'd0),
    .m_axi_mem_BVALID(1'b0),
    .m_axi_mem_BREADY(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_BREADY),
    .m_axi_mem_BRESP(2'd0),
    .m_axi_mem_BID(1'd0),
    .m_axi_mem_BUSER(1'd0),
    .MatA_address0(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_address0),
    .MatA_ce0(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_ce0),
    .MatA_we0(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_we0),
    .MatA_d0(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_d0),
    .MatA_address1(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_address1),
    .MatA_ce1(grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_ce1),
    .MatA_q1(MatA_q1),
    .MatA_DRAM(MatA_DRAM_read_reg_206)
);

real_matmul_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_start),
    .ap_done(grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_done),
    .ap_idle(grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_idle),
    .ap_ready(grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_ready),
    .MatC_address0(grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_address0),
    .MatC_ce0(grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_ce0),
    .MatC_we0(grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_we0),
    .MatC_d0(grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_d0)
);

real_matmul_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_start),
    .ap_done(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_done),
    .ap_idle(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_idle),
    .ap_ready(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_ready),
    .m_axi_mem_AWVALID(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWVALID),
    .m_axi_mem_AWREADY(1'b0),
    .m_axi_mem_AWADDR(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWADDR),
    .m_axi_mem_AWID(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWID),
    .m_axi_mem_AWLEN(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWLEN),
    .m_axi_mem_AWSIZE(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWSIZE),
    .m_axi_mem_AWBURST(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWBURST),
    .m_axi_mem_AWLOCK(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWLOCK),
    .m_axi_mem_AWCACHE(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWCACHE),
    .m_axi_mem_AWPROT(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWPROT),
    .m_axi_mem_AWQOS(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWQOS),
    .m_axi_mem_AWREGION(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWREGION),
    .m_axi_mem_AWUSER(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_AWUSER),
    .m_axi_mem_WVALID(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WVALID),
    .m_axi_mem_WREADY(1'b0),
    .m_axi_mem_WDATA(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WDATA),
    .m_axi_mem_WSTRB(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WSTRB),
    .m_axi_mem_WLAST(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WLAST),
    .m_axi_mem_WID(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WID),
    .m_axi_mem_WUSER(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_WUSER),
    .m_axi_mem_ARVALID(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARVALID),
    .m_axi_mem_ARREADY(mem_ARREADY),
    .m_axi_mem_ARADDR(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARADDR),
    .m_axi_mem_ARID(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARID),
    .m_axi_mem_ARLEN(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARLEN),
    .m_axi_mem_ARSIZE(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARSIZE),
    .m_axi_mem_ARBURST(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARBURST),
    .m_axi_mem_ARLOCK(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARLOCK),
    .m_axi_mem_ARCACHE(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARCACHE),
    .m_axi_mem_ARPROT(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARPROT),
    .m_axi_mem_ARQOS(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARQOS),
    .m_axi_mem_ARREGION(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARREGION),
    .m_axi_mem_ARUSER(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARUSER),
    .m_axi_mem_RVALID(mem_RVALID),
    .m_axi_mem_RREADY(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_RREADY),
    .m_axi_mem_RDATA(mem_RDATA),
    .m_axi_mem_RLAST(1'b0),
    .m_axi_mem_RID(1'd0),
    .m_axi_mem_RFIFONUM(mem_RFIFONUM),
    .m_axi_mem_RUSER(1'd0),
    .m_axi_mem_RRESP(2'd0),
    .m_axi_mem_BVALID(1'b0),
    .m_axi_mem_BREADY(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_BREADY),
    .m_axi_mem_BRESP(2'd0),
    .m_axi_mem_BID(1'd0),
    .m_axi_mem_BUSER(1'd0),
    .MatB_address0(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_address0),
    .MatB_ce0(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_ce0),
    .MatB_we0(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_we0),
    .MatB_d0(grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_d0),
    .sext_ln36(trunc_ln_reg_211)
);

real_matmul_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_start),
    .ap_done(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_done),
    .ap_idle(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_idle),
    .ap_ready(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_ready),
    .MatA_address0(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatA_address0),
    .MatA_ce0(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatA_ce0),
    .MatA_q0(MatA_q0),
    .MatC_address0(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_address0),
    .MatC_ce0(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_ce0),
    .MatC_we0(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_we0),
    .MatC_d0(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_d0),
    .MatC_address1(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_address1),
    .MatC_ce1(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_ce1),
    .MatC_q1(MatC_q1),
    .MatB_address0(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatB_address0),
    .MatB_ce0(grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatB_ce0),
    .MatB_q0(MatB_q0)
);

real_matmul_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_start),
    .ap_done(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_done),
    .ap_idle(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_idle),
    .ap_ready(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_ready),
    .m_axi_mem_AWVALID(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWVALID),
    .m_axi_mem_AWREADY(mem_AWREADY),
    .m_axi_mem_AWADDR(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWADDR),
    .m_axi_mem_AWID(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWID),
    .m_axi_mem_AWLEN(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWLEN),
    .m_axi_mem_AWSIZE(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWSIZE),
    .m_axi_mem_AWBURST(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWBURST),
    .m_axi_mem_AWLOCK(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWLOCK),
    .m_axi_mem_AWCACHE(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWCACHE),
    .m_axi_mem_AWPROT(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWPROT),
    .m_axi_mem_AWQOS(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWQOS),
    .m_axi_mem_AWREGION(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWREGION),
    .m_axi_mem_AWUSER(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWUSER),
    .m_axi_mem_WVALID(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WVALID),
    .m_axi_mem_WREADY(mem_WREADY),
    .m_axi_mem_WDATA(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WDATA),
    .m_axi_mem_WSTRB(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WSTRB),
    .m_axi_mem_WLAST(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WLAST),
    .m_axi_mem_WID(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WID),
    .m_axi_mem_WUSER(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WUSER),
    .m_axi_mem_ARVALID(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARVALID),
    .m_axi_mem_ARREADY(1'b0),
    .m_axi_mem_ARADDR(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARADDR),
    .m_axi_mem_ARID(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARID),
    .m_axi_mem_ARLEN(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARLEN),
    .m_axi_mem_ARSIZE(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARSIZE),
    .m_axi_mem_ARBURST(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARBURST),
    .m_axi_mem_ARLOCK(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARLOCK),
    .m_axi_mem_ARCACHE(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARCACHE),
    .m_axi_mem_ARPROT(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARPROT),
    .m_axi_mem_ARQOS(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARQOS),
    .m_axi_mem_ARREGION(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARREGION),
    .m_axi_mem_ARUSER(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_ARUSER),
    .m_axi_mem_RVALID(1'b0),
    .m_axi_mem_RREADY(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_RREADY),
    .m_axi_mem_RDATA(128'd0),
    .m_axi_mem_RLAST(1'b0),
    .m_axi_mem_RID(1'd0),
    .m_axi_mem_RFIFONUM(9'd0),
    .m_axi_mem_RUSER(1'd0),
    .m_axi_mem_RRESP(2'd0),
    .m_axi_mem_BVALID(mem_BVALID),
    .m_axi_mem_BREADY(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_BREADY),
    .m_axi_mem_BRESP(2'd0),
    .m_axi_mem_BID(1'd0),
    .m_axi_mem_BUSER(1'd0),
    .sext_ln71(trunc_ln3_reg_217),
    .MatC_address0(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_MatC_address0),
    .MatC_ce0(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_MatC_ce0),
    .MatC_q0(MatC_q0)
);

real_matmul_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .MatA_DRAM(MatA_DRAM),
    .MatB_DRAM(MatB_DRAM),
    .MatC_DRAM(MatC_DRAM),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

real_matmul_mem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
mem_m_axi_U(
    .AWVALID(m_axi_mem_AWVALID),
    .AWREADY(m_axi_mem_AWREADY),
    .AWADDR(m_axi_mem_AWADDR),
    .AWID(m_axi_mem_AWID),
    .AWLEN(m_axi_mem_AWLEN),
    .AWSIZE(m_axi_mem_AWSIZE),
    .AWBURST(m_axi_mem_AWBURST),
    .AWLOCK(m_axi_mem_AWLOCK),
    .AWCACHE(m_axi_mem_AWCACHE),
    .AWPROT(m_axi_mem_AWPROT),
    .AWQOS(m_axi_mem_AWQOS),
    .AWREGION(m_axi_mem_AWREGION),
    .AWUSER(m_axi_mem_AWUSER),
    .WVALID(m_axi_mem_WVALID),
    .WREADY(m_axi_mem_WREADY),
    .WDATA(m_axi_mem_WDATA),
    .WSTRB(m_axi_mem_WSTRB),
    .WLAST(m_axi_mem_WLAST),
    .WID(m_axi_mem_WID),
    .WUSER(m_axi_mem_WUSER),
    .ARVALID(m_axi_mem_ARVALID),
    .ARREADY(m_axi_mem_ARREADY),
    .ARADDR(m_axi_mem_ARADDR),
    .ARID(m_axi_mem_ARID),
    .ARLEN(m_axi_mem_ARLEN),
    .ARSIZE(m_axi_mem_ARSIZE),
    .ARBURST(m_axi_mem_ARBURST),
    .ARLOCK(m_axi_mem_ARLOCK),
    .ARCACHE(m_axi_mem_ARCACHE),
    .ARPROT(m_axi_mem_ARPROT),
    .ARQOS(m_axi_mem_ARQOS),
    .ARREGION(m_axi_mem_ARREGION),
    .ARUSER(m_axi_mem_ARUSER),
    .RVALID(m_axi_mem_RVALID),
    .RREADY(m_axi_mem_RREADY),
    .RDATA(m_axi_mem_RDATA),
    .RLAST(m_axi_mem_RLAST),
    .RID(m_axi_mem_RID),
    .RUSER(m_axi_mem_RUSER),
    .RRESP(m_axi_mem_RRESP),
    .BVALID(m_axi_mem_BVALID),
    .BREADY(m_axi_mem_BREADY),
    .BRESP(m_axi_mem_BRESP),
    .BID(m_axi_mem_BID),
    .BUSER(m_axi_mem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(mem_ARVALID),
    .I_CH0_ARREADY(mem_ARREADY),
    .I_CH0_ARADDR(mem_ARADDR),
    .I_CH0_ARLEN(mem_ARLEN),
    .I_CH0_RVALID(mem_RVALID),
    .I_CH0_RREADY(mem_RREADY),
    .I_CH0_RDATA(mem_RDATA),
    .I_CH0_RFIFONUM(mem_RFIFONUM),
    .I_CH0_AWVALID(mem_AWVALID),
    .I_CH0_AWREADY(mem_AWREADY),
    .I_CH0_AWADDR(mem_AWADDR),
    .I_CH0_AWLEN(mem_AWLEN),
    .I_CH0_WVALID(mem_WVALID),
    .I_CH0_WREADY(mem_WREADY),
    .I_CH0_WDATA(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WDATA),
    .I_CH0_WSTRB(grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WSTRB),
    .I_CH0_BVALID(mem_BVALID),
    .I_CH0_BREADY(mem_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((mem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state147))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call18) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_start_reg <= 1'b1;
        end else if ((grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_ready == 1'b1)) begin
            grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state74)) begin
            grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_start_reg <= 1'b1;
        end else if ((grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_ready == 1'b1)) begin
            grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call24) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_start_reg <= 1'b1;
        end else if ((grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_ready == 1'b1)) begin
            grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state78)) begin
            grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_start_reg <= 1'b1;
        end else if ((grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_ready == 1'b1)) begin
            grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state76)) begin
            grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_start_reg <= 1'b1;
        end else if ((grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_ready == 1'b1)) begin
            grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        MatA_DRAM_read_reg_206 <= MatA_DRAM;
        trunc_ln3_reg_217 <= {{MatC_DRAM[63:4]}};
        trunc_ln_reg_211 <= {{MatB_DRAM[63:4]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        MatA_address0 = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatA_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        MatA_address0 = grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_address0;
    end else begin
        MatA_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        MatA_ce0 = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatA_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        MatA_ce0 = grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_ce0;
    end else begin
        MatA_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        MatA_ce1 = grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_ce1;
    end else begin
        MatA_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        MatA_we0 = grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_MatA_we0;
    end else begin
        MatA_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        MatB_address0 = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatB_address0;
    end else if ((1'b1 == ap_CS_fsm_state75)) begin
        MatB_address0 = grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_address0;
    end else begin
        MatB_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        MatB_ce0 = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatB_ce0;
    end else if ((1'b1 == ap_CS_fsm_state75)) begin
        MatB_ce0 = grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_ce0;
    end else begin
        MatB_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        MatB_we0 = grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_MatB_we0;
    end else begin
        MatB_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state79)) begin
        MatC_address0 = grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_MatC_address0;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        MatC_address0 = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        MatC_address0 = grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_address0;
    end else begin
        MatC_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state79)) begin
        MatC_ce0 = grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_MatC_ce0;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        MatC_ce0 = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        MatC_ce0 = grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_ce0;
    end else begin
        MatC_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        MatC_ce1 = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_ce1;
    end else begin
        MatC_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        MatC_d0 = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        MatC_d0 = grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_d0;
    end else begin
        MatC_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        MatC_we0 = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_MatC_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        MatC_we0 = grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_MatC_we0;
    end else begin
        MatC_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

assign ap_ST_fsm_state102_blk = 1'b0;

assign ap_ST_fsm_state103_blk = 1'b0;

assign ap_ST_fsm_state104_blk = 1'b0;

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state110_blk = 1'b0;

assign ap_ST_fsm_state111_blk = 1'b0;

assign ap_ST_fsm_state112_blk = 1'b0;

assign ap_ST_fsm_state113_blk = 1'b0;

assign ap_ST_fsm_state114_blk = 1'b0;

assign ap_ST_fsm_state115_blk = 1'b0;

assign ap_ST_fsm_state116_blk = 1'b0;

assign ap_ST_fsm_state117_blk = 1'b0;

assign ap_ST_fsm_state118_blk = 1'b0;

assign ap_ST_fsm_state119_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state120_blk = 1'b0;

assign ap_ST_fsm_state121_blk = 1'b0;

assign ap_ST_fsm_state122_blk = 1'b0;

assign ap_ST_fsm_state123_blk = 1'b0;

assign ap_ST_fsm_state124_blk = 1'b0;

assign ap_ST_fsm_state125_blk = 1'b0;

assign ap_ST_fsm_state126_blk = 1'b0;

assign ap_ST_fsm_state127_blk = 1'b0;

assign ap_ST_fsm_state128_blk = 1'b0;

assign ap_ST_fsm_state129_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state130_blk = 1'b0;

assign ap_ST_fsm_state131_blk = 1'b0;

assign ap_ST_fsm_state132_blk = 1'b0;

assign ap_ST_fsm_state133_blk = 1'b0;

assign ap_ST_fsm_state134_blk = 1'b0;

assign ap_ST_fsm_state135_blk = 1'b0;

assign ap_ST_fsm_state136_blk = 1'b0;

assign ap_ST_fsm_state137_blk = 1'b0;

assign ap_ST_fsm_state138_blk = 1'b0;

assign ap_ST_fsm_state139_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state140_blk = 1'b0;

assign ap_ST_fsm_state141_blk = 1'b0;

assign ap_ST_fsm_state142_blk = 1'b0;

assign ap_ST_fsm_state143_blk = 1'b0;

assign ap_ST_fsm_state144_blk = 1'b0;

assign ap_ST_fsm_state145_blk = 1'b0;

assign ap_ST_fsm_state146_blk = 1'b0;

always @ (*) begin
    if ((mem_BVALID == 1'b0)) begin
        ap_ST_fsm_state147_blk = 1'b1;
    end else begin
        ap_ST_fsm_state147_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((mem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

always @ (*) begin
    if ((grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_done == 1'b0)) begin
        ap_ST_fsm_state75_blk = 1'b1;
    end else begin
        ap_ST_fsm_state75_blk = 1'b0;
    end
end

assign ap_ST_fsm_state76_blk = 1'b0;

always @ (*) begin
    if (((grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_done == 1'b0) | (mem_AWREADY == 1'b0))) begin
        ap_ST_fsm_state77_blk = 1'b1;
    end else begin
        ap_ST_fsm_state77_blk = 1'b0;
    end
end

assign ap_ST_fsm_state78_blk = 1'b0;

always @ (*) begin
    if ((grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_done == 1'b0)) begin
        ap_ST_fsm_state79_blk = 1'b1;
    end else begin
        ap_ST_fsm_state79_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

assign ap_ST_fsm_state96_blk = 1'b0;

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((mem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state147))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((mem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state147))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        mem_ARADDR = sext_ln36_fu_186_p1;
    end else if (((1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74))) begin
        mem_ARADDR = grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        mem_ARADDR = grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARADDR;
    end else begin
        mem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        mem_ARLEN = 64'd3750;
    end else if (((1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74))) begin
        mem_ARLEN = grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        mem_ARLEN = grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARLEN;
    end else begin
        mem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        mem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74))) begin
        mem_ARVALID = grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        mem_ARVALID = grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_ARVALID;
    end else begin
        mem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_done == 1'b0) | (mem_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state77))) begin
        mem_AWADDR = sext_ln71_fu_196_p1;
    end else if (((1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78))) begin
        mem_AWADDR = grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWADDR;
    end else begin
        mem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_done == 1'b0) | (mem_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state77))) begin
        mem_AWLEN = 64'd2500;
    end else if (((1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78))) begin
        mem_AWLEN = grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWLEN;
    end else begin
        mem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_done == 1'b0) | (mem_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state77))) begin
        mem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78))) begin
        mem_AWVALID = grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_AWVALID;
    end else begin
        mem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((mem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state147))) begin
        mem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78))) begin
        mem_BREADY = grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_BREADY;
    end else begin
        mem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74))) begin
        mem_RREADY = grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_m_axi_mem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        mem_RREADY = grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_m_axi_mem_RREADY;
    end else begin
        mem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78))) begin
        mem_WVALID = grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_m_axi_mem_WVALID;
    end else begin
        mem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mem_blk_n_AR = m_axi_mem_ARREADY;
    end else begin
        mem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        mem_blk_n_AW = m_axi_mem_AWREADY;
    end else begin
        mem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state147)) begin
        mem_blk_n_B = m_axi_mem_BVALID;
    end else begin
        mem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            if (((grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state75))) begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            if ((~((grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_done == 1'b0) | (mem_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state77))) begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            if (((grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state79))) begin
                ap_NS_fsm = ap_ST_fsm_state80;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state79;
            end
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            ap_NS_fsm = ap_ST_fsm_state135;
        end
        ap_ST_fsm_state135 : begin
            ap_NS_fsm = ap_ST_fsm_state136;
        end
        ap_ST_fsm_state136 : begin
            ap_NS_fsm = ap_ST_fsm_state137;
        end
        ap_ST_fsm_state137 : begin
            ap_NS_fsm = ap_ST_fsm_state138;
        end
        ap_ST_fsm_state138 : begin
            ap_NS_fsm = ap_ST_fsm_state139;
        end
        ap_ST_fsm_state139 : begin
            ap_NS_fsm = ap_ST_fsm_state140;
        end
        ap_ST_fsm_state140 : begin
            ap_NS_fsm = ap_ST_fsm_state141;
        end
        ap_ST_fsm_state141 : begin
            ap_NS_fsm = ap_ST_fsm_state142;
        end
        ap_ST_fsm_state142 : begin
            ap_NS_fsm = ap_ST_fsm_state143;
        end
        ap_ST_fsm_state143 : begin
            ap_NS_fsm = ap_ST_fsm_state144;
        end
        ap_ST_fsm_state144 : begin
            ap_NS_fsm = ap_ST_fsm_state145;
        end
        ap_ST_fsm_state145 : begin
            ap_NS_fsm = ap_ST_fsm_state146;
        end
        ap_ST_fsm_state146 : begin
            ap_NS_fsm = ap_ST_fsm_state147;
        end
        ap_ST_fsm_state147 : begin
            if (((mem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state147))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state147;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state147 = ap_CS_fsm[32'd146];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state79 = ap_CS_fsm[32'd78];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call18 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call24 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_done == 1'b0) | (grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_done == 1'b0));
end

assign grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_start = grp_real_matmul_Pipeline_MAT_A_ROWS_MAT_A_COLS_fu_127_ap_start_reg;

assign grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_start = grp_real_matmul_Pipeline_MAT_B_ROWS_MAT_B_COLS_fu_143_ap_start_reg;

assign grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_start = grp_real_matmul_Pipeline_MAT_C_ROWS_INIT_MAT_C_COLS_INIT_fu_137_ap_start_reg;

assign grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_start = grp_real_matmul_Pipeline_MAT_C_ROWS_MAT_C_COLS_fu_158_ap_start_reg;

assign grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_start = grp_real_matmul_Pipeline_OUTER_ROWS_OUTER_COLS_fu_151_ap_start_reg;

assign sext_ln36_fu_186_p1 = $signed(trunc_ln_reg_211);

assign sext_ln71_fu_196_p1 = $signed(trunc_ln3_reg_217);

endmodule //real_matmul
